export default [
  {
    q: "Ta boisson préférée en soirée ?",
    a: [
      "Passoa",
      "365",
      "Gin",
      "Gordon (flash)",
      "Mousseux",
      "Vodka",
      "Jupiler",
      "Cara",
      "Jus de pomme",
    ],
  },
  {
    q: "Ta citation préférée ?",
    a: [
      "Tant qu'il y a pelouse il y a match",
      "Mieux vaut que ça sorte du grenier que de la cave",
      "J'aimerais être ami avec moi-même",
      "Si t'aimes pas ce que tu vois, pourquoi tu mattes ?",
      "Joe sces quiéyeière ér ér ér",
      "Je vous emmerde et je rentre à la maison",
      "Faut que ça swing",
      "Tout le monde il est mon copain",
      "La qualité plutôt que la quantité",
    ],
  },
  {
    q: "Ta musique préférée ?",
    a: [
      "Toxic - Britney Spears",
      "Big Orgus - DJ Furax",
      "Chui bo - PZK",
      "Déshabillez-moi - Mylène Farmer",
      "Chacarron - El Chombo",
      "Ca m'énerve - Helmut Fritz",
      "N'importe, je les connais toutes",
      "Bienvenue dans la secte - La Secte Phonétik",
      "La musique du film Batman",
    ],
  },
  {
    q: "L'avantage de t'avoir dans un staff ?",
    a: [
      "Tu alimentes les ragots",
      "Tu connais la moitié des fermiers en Belgique, pratique pour chopper une prairie",
      "Bah, avoir le privilège de te cotoyer, quelle question",
      "Tes affaires prennent pas beaucoup de place au camp, t'as pris approximativement 6 vêtements",
      "T'es plein de sagesse, même si les gens ont pas l'air de le remarquer",
      "Pas de controverses ou débat dans le staff, vu que tout le monde a peur de toi",
      "Pas besoin d'allumer un feu pour se réchauffer, tu t'arrêtes jamais de bouger",
      'Ah bah tu mets la bonne ambiance! "Michel c\'est le brésil, il danse la samba, il va de ville en ville pour vendre des velux!"',
      "T'es toujours frais les lendemains de teufs... Puisque tu teufes pas",
    ],
  },
  {
    q: "Qu'est-ce qui est le plus important chez un intendnant selon toi ?",
    a: [
      "Son cul",
      "Qu'il/elle sache traire une vache pour avoir du lait le matin",
      "Son admiration pour toi, chef parfait",
      "Qu'il/elle soit pas vite gêné(e)",
      "Qu'il/elle te comprenne",
      "Qu'il/elle te fasse chier parce qu'il/elle ne trouve pas les assiettes",
      "Qu'il/elle sache danser le rock, pour enfin faire un duo",
      "Qu'il/elle adore faire la teuf",
      "Qu'il/elle aime bien passer ses soirées à discuter de sujet profonds",
    ],
  },
  {
    q: "Ton chef d'U préféré ?",
    a: [
      "Ludo",
      "Pingouin",
      "Didier",
      "Annabelle",
      "Manu",
      "Denis",
      "Patricia",
      "Yoric",
      "Pascal",
    ],
  },
  {
    q: "Ton animal spirituel ?",
    a: [
      "Requin",
      "Vache",
      "Lama",
      "Babouin",
      "Girafe",
      "Frelon",
      "Pingouin",
      "Chien",
      "Chauve-souris",
    ],
  },
  {
    q:
      "Tu fais malencontreusement tomber une bière en soirée, qu'en penses-tu ?",
    a: [
      "En espérent que quelqu'un ramasse, bend over",
      "Nouarf, ça tombera pas plus bas",
      "Je vais quand même pas m'abaisser pour la ramasser, un sous-fifre le fera pour moi",
      "Heureusement que tes vêtements étaient au sol pour amortir sa chute",
      "Tu essaies de t'excuser mais personne t'écoute de toute façon",
      "Tu cherches quelqu'un qui passe une bonne soirée et tu vas l'engueuler parce qu'il ne t'avait pas prévenu que la bière était là",
      "Ce sont des choses qui arrivent quand les gens mettent des choses sur ton chemin quand tu fais un grand jeté",
      "Bière renversée bière affonée, t’es parti(e)",
      "Tu proposes d’aller en rechercher dans la réserve, mais tu profites pour y rester et matter les étoiles pendant 3 heures",
    ],
  },
  {
    q: "Ta danse préférée en teuf",
    a: [
      "Le twerk, mais quand je regarde des gens le danser",
      "Peu importe, tant que c’est sur le bar",
      "Je ne danse pas",
      "Hélicoptère, hélicoptère, hélicoptère avec ma...",
      "Le robot",
      "La tektonik, avec un peu de chances quelqu’un passera à côté et tu pourras lui mettre une mandale ni vu ni connu",
      "Pourquoi se limiter à une?",
      "La macarena",
      "Les moves de dance stylés des années 90",
    ],
  },
  {
    q: "Des externes débarquent au bar pi, qu’en penses-tu?",
    a: [
      "De la chair fraîche, miam.",
      "Eh là c’est parti pour un affond apollo 13 de bienvenue!",
      "Nice, des nouveaux gens à qui parler de moi.",
      "Ah, bah non, ils t’ont vu à poil et ils ont fait demi-tour",
      "“Ah! En espérant que leur audition soit meilleure que celle des gens de Ste-Anne “",
      "“Putain, déjà que la moitié des gens à cette teuf me font déjà chier...”",
      "“Baddant, ça fait moins de place sur le dancefloor”",
      "“On s’affone?”",
      "“Yes, ça va être plus facile de me tirer en douce maintenant”",
    ],
  },
  {
    q: "L'avantage de t’avoir dans un staff?",
    a: [
      "Tu alimentes les ragots",
      "Tu connais la moitié des fermiers en Belgique, pratique pour choper une prairie",
      "Bah, avoir le privilège de te côtoyer, quelle question",
      "Tes affaires prennent pas beaucoup de place en camp, t'as pris approximativement 6 vêtements",
      "T’es plein de sagesse, même si les gens ont pas l’air de le remarquer",
      "Pas de controverses ou débats dans le staff, vu que tout le monde a peur de toi",
      "Pas besoin d’allumer un feu pour se réchauffer, tu t’arrêtes jamais de bouger",
      "Ah bah tu mets la bonne ambiance! “Michel c’est le brésil il danse la samba, il va de ville en ville pour vendre des velux!”",
      "T’es toujours frais les lendemains de teufs... Puisque tu teufes pas",
    ],
  },
];
