export default [
  {
    q: "Ta boisson préférée en soirée ?",
    a: {
      0: "Passoa",
      1: "365",
      2: "Gin",
      3: "Gordon (flash)",
      4: "Mousseux",
      5: "Vodka",
      6: "Jupiler",
      7: "Cara",
      8: "Jus de pomme",
    },
  },
  {
    q: "Ta citation préférée ?",
    a: {
      0: "Tant qu'il y a pelouse il y a match",
      1: "Mieux vaut que ça sorte du grenier que de la cave",
      2: "J'aimerais être ami avec moi-même",
      3: "Si t'aimes pas ce que tu vois, pourquoi tu mattes ?",
      4: "Joe sces quiéyeière ér ér ér",
      5: "Je vous emmerde et je rentre à la maison",
      6: "Faut que ça swing",
      7: "Tout le monde il est mon copain",
      8: "La qualité plutôt que la quantité",
    },
  },
  {
    q: "Ta musique préférée ?",
    a: {
      0: "Toxic - Britney Spears",
      1: "Big Orgus - DJ Furax",
      2: "Chui bo - PZK",
      3: "Déshabillez-moi - Mylène Farmer",
      4: "Chacarron - El Chombo",
      5: "Ca m'énerve - Helmut Fritz",
      6: "N'importe, je les connais toutes",
      7: "Bienvenue dans la secte - La Secte Phonétik",
      8: "La musique du film Batman",
    },
  },
  {
    q: "L'avantage de t'avoir dans un staff ?",
    a: {
      0: "Tu alimentes les ragots",
      1: "Tu connais la moitié des fermiers en Belgique, pratique pour chopper une prairie",
      2: "Bah, avoir le privilège de te cotoyer, quelle question",
      3: "Tes affaires prennent pas beaucoup de place au camp, t'as pris approximativement 6 vêtements",
      4: "T'es plein de sagesse, même si les gens ont pas l'air de le remarquer",
      5: "Pas de controverses ou débat dans le staff, vu que tout le monde a peur de toi",
      6: "Pas besoin d'allumer un feu pour se réchauffer, tu t'arrêtes jamais de bouger",
      7: 'Ah bah tu mets la bonne ambiance! "Michel c\'est le brésil, il danse la samba, il va de ville en ville pour vendre des velux!"',
      8: "T'es toujours frais les lendemains de teufs... Puisque tu teufes pas",
    },
  },
  {
    q: "Qu'est-ce qui est le plus important chez un intendnant selon toi ?",
    a: {
      0: "Son cul",
      1: "Qu'il/elle sache traire une vache pour avoir du lait le matin",
      2: "Son admiration pour toi, chef parfait",
      3: "Qu'il/elle soit pas vite gêné(e)",
      4: "Qu'il/elle te comprenne",
      5: "Qu'il/elle te fasse chier parce qu'il/elle ne trouve pas les assiettes",
      6: "Qu'il/elle sache danser le rock, pour enfin faire un duo",
      7: "Qu'il/elle adore faire la teuf",
      8: "Qu'il/elle aime bien passer ses soirées à discuter de sujet profonds",
    },
  },
  {
    q: "Ton chef d'U préféré ?",
    a: {
      0: "Ludo",
      1: "Pingouin",
      2: "Didier",
      3: "Annabelle",
      4: "Manu",
      5: "Denis",
      6: "Patricia",
      7: "Yoric",
      8: "Pascal",
    },
  },
  {
    q: "Ton animal spirituel ?",
    a: {
      0: "Requin",
      1: "Vache",
      2: "Lama",
      3: "Babouin",
      4: "Girafe",
      5: "Frelon",
      6: "Pingouin",
      7: "Chien",
      8: "Chauve-souris",
    },
  },
  {
    q:
      "Tu fais malencontreusement tomber une bière en soirée, qu'en penses-tu ?",
    a: {
      0: "En espérent que quelqu'un ramasse, bend over",
      1: "Nouarf, ça tombera pas plus bas",
      2: "Je vais quand même pas m'abaisser pour la ramasser, un sous-fifre le fera pour moi",
      3: "Heureusement que tes vêtements étaient au sol pour amortir sa chute",
      4: "Tu essaies de t'excuser mais personne t'écoute de toute façon",
      5: "Tu cherches quelqu'un qui passe une bonne soirée et tu vas l'engueuler parce qu'il ne t'avait pas prévenu que la bière était là",
      6: "Ce sont des choses qui arrivent quand les gens mettent des choses sur ton chemin quand tu fais un grand jeté",
      7: "Bière renversée bière affonée, t’es parti(e)",
      8: "Tu proposes d’aller en rechercher dans la réserve, mais tu profites pour y rester et matter les étoiles pendant 3 heures",
    },
  },
  {
    q: "Ta danse préférée en teuf",
    a: {
      0: "Le twerk, mais quand je regarde des gens le danser",
      1: "Peu importe, tant que c’est sur le bar",
      2: "Je ne danse pas",
      3: "Hélicoptère, hélicoptère, hélicoptère avec ma...",
      4: "Le robot",
      5: "La tektonik, avec un peu de chances quelqu’un passera à côté et tu pourras lui mettre une mandale ni vu ni connu",
      6: "Pourquoi se limiter à une?",
      7: "La macarena",
      8: "Les moves de dance stylés des années 90",
    },
  },
  {
    q: "Des externes débarquent au bar pi, qu’en penses-tu?",
    a: {
      0: "De la chair fraîche, miam.",
      1: "Eh là c’est parti pour un affond apollo 13 de bienvenue!",
      2: "Nice, des nouveaux gens à qui parler de moi.",
      3: "Ah, bah non, ils t’ont vu à poil et ils ont fait demi-tour",
      4: "“Ah! En espérant que leur audition soit meilleure que celle des gens de Ste-Anne “",
      5: "“Putain, déjà que la moitié des gens à cette teuf me font déjà chier...”",
      6: "“Baddant, ça fait moins de place sur le dancefloor”",
      7: "“On s’affone?”",
      8: "“Yes, ça va être plus facile de me tirer en douce maintenant”",
    },
  },
  {
    q: "L'avantage de t’avoir dans un staff?",
    a: {
      0: "Tu alimentes les ragots",
      1: "Tu connais la moitié des fermiers en Belgique, pratique pour choper une prairie",
      2: "Bah, avoir le privilège de te côtoyer, quelle question",
      3: "Tes affaires prennent pas beaucoup de place en camp, t'as pris approximativement 6 vêtements",
      4: "T’es plein de sagesse, même si les gens ont pas l’air de le remarquer",
      5: "Pas de controverses ou débats dans le staff, vu que tout le monde a peur de toi",
      6: "Pas besoin d’allumer un feu pour se réchauffer, tu t’arrêtes jamais de bouger",
      7: "Ah bah tu mets la bonne ambiance! “Michel c’est le brésil il danse la samba, il va de ville en ville pour vendre des velux!”",
      8: "T’es toujours frais les lendemains de teufs... Puisque tu teufes pas",
    },
  },
];
